name: Autograding

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Тест 1: Вставить картинку
      - name: Test image tag
        run: |
          grep -i -q '<img[^>]*src=' index.html \
          && echo "✅ Image tag found" \
          || echo "❌ Image tag not found"
        continue-on-error: true

      # Тест 2: Ссылка-картинка на Google
      - name: Test image link
        run: |
          tr -d '\n' < index.html | grep -Ei -q '<a\s*href="https?://(www\.)?google\.com"[^>]*>\s*<img[^>]*>\s*</a>' \
          && echo "✅ Image link to Google found" \
          || echo "❌ Image link to Google not found"
        continue-on-error: true

      # Тест 3: Вложенный список
      - name: Test nested list
        run: |
          tr -d '\n' < index.html | grep -Eq '<li[^>]*>.*<(ul|ol)[^>]*>'\
          && echo "✅ Nested list found" \
          || echo "❌ Nested list not found"
        continue-on-error: true

      # Тест 4: Список определений
      - name: Test definition list
        run: |
          tr -d '\n' < index.html | grep -Ei '<li[^>]*>.*<(ul|ol)[^>]*>'\
          && echo "✅ Definition list found" \
          || echo "❌ Definition list not found"
        continue-on-error: true

      # Тест 5: Тег <pre>
      - name: Test pre tag
        run: |
          grep -iq '<pre>' index.html \
          && echo "✅ <pre> tag found" \
          || echo "❌ <pre> tag not found"
        continue-on-error: true

      # Тест 6: Форматирование текста
      - name: Test text formatting
        run: |
          tr -d '\n' < index.html | grep -Ei -q '<b>\s*<u>.*</u>\s*</b>' \
          && echo "✅ Bold+Underline formatting found" \
          || echo "❌ Bold+Underline formatting not found"
        continue-on-error: true
